package com.example.test.mapper;

import com.example.test.bean.productDO;

public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Apr 14 14:28:55 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Apr 14 14:28:55 GMT+08:00 2020
     */
    int insert(productDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Apr 14 14:28:55 GMT+08:00 2020
     */
    int insertSelective(productDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Apr 14 14:28:55 GMT+08:00 2020
     */
    productDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Apr 14 14:28:55 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(productDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Apr 14 14:28:55 GMT+08:00 2020
     */
    int updateByPrimaryKey(productDO record);

    int checkPriceByPname(String pName);
}